first pass new render
broadinstitute/firecloud-orchestration pull request #1447
Opened 2024-10-04 19:56 UTC by calypsomatic

\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge. Make sure your branch deletes; GitHub should do this for you.
- [ ] Test this change deployed correctly and works on dev environment after deployment

2024-10-04 20:52 UTC, davidangb requested changes
one change necessary to a docker image, otherwise looks good

2024-10-04 20:52 UTC, davidangb commented on local-dev/templates/docker-rsync-local-orch.sh
>      -e JAVA_OPTS="$DOCKER_JAVA_OPTS" \
the line just below this (which I can't comment on via the github UI) is incorrect. See https://github.com/broadinstitute/firecloud-orchestration/pull/1444 … the docker image tag needs an update to `eclipse-temurin-jammy-17.0.10_7_1.10.2_2.13.15`.

Maybe this PR just needs to be rebased against `develop`

2024-10-04 20:55 UTC, davidangb approved these changes
giving this a proactive :+1: so you're not waiting on me, with the assumption you'll fix the docker image

2024-10-07 14:43 UTC, kevinmarete approved these changes

2024-10-07 15:01 UTC, merged