Ah gabw 1708: Orch changes to support catalog permissions
broadinstitute/firecloud-orchestration pull request #406
Opened 2017-03-20 19:27 UTC by ahaessly

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-03-21 17:59 UTC, davidangb requested changes
comments inline!

2017-03-21 17:59 UTC, davidangb commented on project/Dependencies.scala
> +    "org.broadinstitute.dsde" %%  "rawls-model"  % "0.1-452657e-SNAP"
once your rawls PR merges, this will change, right?

2017-03-21 17:59 UTC, davidangb commented on src/main/scala/org/broadinstitute/dsde/firecloud/utils/PermissionsSupport.scala
> +      true
always returns true?

2017-03-21 17:59 UTC, davidangb commented on src/main/scala/org/broadinstitute/dsde/firecloud/utils/PermissionsSupport.scala
> +
the three methods below this are not used anywhere in the code, according to IntelliJ. Do we still need them?

2017-03-21 17:59 UTC, davidangb commented on src/test/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceApiServiceSpec.scala
> +//            val resp = respdata.usersUpdated.head
remove comments

2017-03-21 17:59 UTC, davidangb commented on src/main/scala/org/broadinstitute/dsde/firecloud/utils/PermissionsSupport.scala
> +  }
I think you should keep the `asAdmin` and `asCurator` pattern going here, and add something like:
```
  def asPermitted(ns: String, name: String, lvl: WorkspaceAccessLevel, userInfo: UserInfo)(op: => Future[PerRequestMessage]): Future[PerRequestMessage] = {
    hasAccessOrAdmin(ns, name, lvl, userInfo) flatMap { isPermitted =>
      if (isPermitted) op else Future.failed(new FireCloudExceptionWithErrorReport(errorReport = ErrorReport(StatusCodes.Forbidden, s"You must have at least ${lvl.toString} access.")))
    }
  }
```

if you have that, then you can simplify the methods in WorkspaceService, for example:
```
  def getCatalog(workspaceNamespace: String, workspaceName: String, userInfo: UserInfo): Future[PerRequestMessage] = {
    asPermitted(workspaceNamespace, workspaceName, WorkspaceAccessLevels.Read, userInfo) {
      rawlsDAO.getCatalog(workspaceNamespace, workspaceName) map (RequestComplete(_))
    }
  }
```

disclaimer: I haven't actually tried this outside of unit tests.

2017-03-21 17:59 UTC, davidangb commented on src/main/resources/swagger/api-docs.yaml
> +          description: Insufficient permissions to get workspace ACLs (must be owner or admin)
"workspace ACLs" or "catalog permissions" (or something else)?

2017-03-21 17:59 UTC, davidangb commented on src/main/resources/swagger/api-docs.yaml
> +          description: Attempting to change access controls you can't (your own, or public-access group)
description seems wrong

2017-03-21 17:59 UTC, davidangb commented on src/main/resources/swagger/api-docs.yaml
> +          description: Insufficient permissions to edit workspace ACLs (must be owner)
"workspace ACLs" or "catalog permissions" (or something else)?

2017-03-21 17:59 UTC, davidangb commented on src/main/resources/swagger/api-docs.yaml
> +      description: Edit access control list for a workspace
catalog permissions

2017-03-21 17:59 UTC, davidangb commented on src/main/scala/org/broadinstitute/dsde/firecloud/service/WorkspaceService.scala
> +        Future.successful(RequestCompleteWithErrorReport(Forbidden, "must be an owner or admin to set catalog permissions"))
see comment below about an `asPermitted` wrapper. If you *don't* implement `asPermitted`, this should be `Future.failed` (same for getCatalog).

2017-03-21 18:08 UTC, ahaessly commented on project/Dependencies.scala
> +    "org.broadinstitute.dsde" %%  "rawls-model"  % "0.1-452657e-SNAP"
yes

2017-03-21 18:47 UTC, davidangb reviewed
looking good! Just need to hold this until rawls merges so you can get the version number for the model jar.

2017-03-22 14:19 UTC, rushtong approved these changes
👍  Pending the answer to 403s.

2017-03-22 14:19 UTC, rushtong commented on src/main/resources/swagger/api-docs.yaml
> +            $ref: '#/definitions/ErrorReport'
Does the 403 leak too much information? We don't return a 403 for regular workspace calls and treat them as 404's. Also applies to other calls as well.

2017-03-22 15:25 UTC, ahaessly commented on src/main/resources/swagger/api-docs.yaml
> +            $ref: '#/definitions/ErrorReport'
Yes, for the get we will return a 404, but for the patch, we will return a 403 if they have read or write but not owner or admin.

2017-03-22 16:54 UTC, davidangb approved these changes

2017-03-22 16:55 UTC, davidangb commented
:+1: as soon as tests pass!

2017-03-22 16:56 UTC, merged