mtalbott add me param
broadinstitute/firecloud-orchestration pull request #670
Opened 2018-08-13 21:00 UTC by marctalbott

Change /me endpoint to accept a parameter which utilizes the register/user/v2/self/info endpoint instead of the register/user/v1 endpoint to cutdown on expensive calls to populate the google field

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

2018-08-13 21:40 UTC, gpolumbo-broad approved these changes

2018-08-13 21:40 UTC, gpolumbo-broad commented on src/main/scala/org/broadinstitute/dsde/firecloud/webservice/UserApiService.scala
> +          authorizationHeader match {
I'm trying to figure out what you changed vs. what git _thinks_ you changed.  I think I count at least 4 neseted case statements, on top of the normal akka nesting.  With caution, I would recommend that if you're making changes here, try to start extracting these nested statements into their own methods.  

This is the sort of thing I'd normally reject a PR for, but seeing as it doesn't seem like you are leaving the code in any worse shape than when you started (I think, it's hard to tell, and that's part of the problem) I'm not going to worry too much about it.

2018-08-13 21:40 UTC, gpolumbo-broad commented on src/test/scala/org/broadinstitute/dsde/firecloud/service/UserApiServiceSpec.scala
> +          )
There are different style preferences in the tests about copy/pasting mocking setup statements like these between tests.  I prefer to treat your testing code as you would production code and keep it DRY and extract the copy/pasted stuff out into its own method.  Do what you want here.

2018-08-13 21:50 UTC, gpolumbo-broad commented
@marctalbott @Qi77Qi not sure if you have been granted access to Codacy yet:  https://app.codacy.com/app/BroadInstitute/firecloud-orchestration/pullRequest?prid=2038494 here's the link to the analysis for this branch, which is in good shape based on the rules being enforced at the moment.  Of particular note, the cyclometric complexity rule is disabled.  Anyway, we should make sure you have access.

2018-08-24 15:47 UTC, MatthewBemis approved these changes

2018-09-07 01:52 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/firecloud/webservice/UserApiService.scala
> +              val version2 = userDetailsOnly.exists(_.equalsIgnoreCase("true"))
do we have to support both v1 and v2?

2018-09-07 13:38 UTC, dvoet requested changes
assuming we want to continue support of /me v1, the api should be composed of the 2 new sam v2 api calls. The intent is that the sam v1 api is deprecated so we should stop using it. I think that also might simplify things a little: always do the sam info call then add in the sam details call if supporting v1.

2018-09-12 11:55 UTC, dvoet approved these changes

2018-09-17 21:01 UTC, merged