[AS-719]: Use base 2 when calculating cost/gb
broadinstitute/firecloud-orchestration pull request #847
Opened 2021-04-09 00:39 UTC by yonghaoy

\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

2021-04-09 12:00 UTC, yonghaoy commented
jenkins retest

2021-04-09 15:35 UTC, wnojopra requested changes
I believe you'll also need to update the test in [WorkspaceApiServiceSpec](https://github.com/broadinstitute/firecloud-orchestration/blob/623cb988d1556b33d53d9f3455e5c3b912f7ee32/src/test/scala/org/broadinstitute/dsde/firecloud/webservice/WorkspaceApiServiceSpec.scala#L1372)

2021-04-12 14:20 UTC, MatthewBemis approved these changes
👍 from me, pending a successful re-run of unit tests

2021-04-12 15:41 UTC, wnojopra approved these changes
LGTM

2021-04-12 15:47 UTC, merged